--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/elt0khy/Documents/Random GIMP/Arch Background2.png"

-- Special
background="#0b0c0c"
foreground="#c0c0c0"
cursor="#c0c0c0"

-- Colors
color0="#0b0c0c"
color1="#218D75"
color2="#239D82"
color3="#23B292"
color4="#7F8080"
color5="#24C19F"
color6="#24D1AC"
color7="#c0c0c0"
color8="#868686"
color9="#218D75"
color10="#239D82"
color11="#23B292"
color12="#7F8080"
color13="#24C19F"
color14="#24D1AC"
color15="#c0c0c0"
