# Shell variables
# Generated by 'wal'
wallpaper='/home/elt0khy/Documents/Random GIMP/Arch Background2.png'

# Special
background='#000000'
foreground='#ffffff'
cursor='#ffffff'

# Colors
color0='#0b0c0c'
color1='#218D75'
color2='#239D82'
color3='#23B292'
color4='#7F8080'
color5='#24C19F'
color6='#24D1AC'
color7='#c0c0c0'
color8='#868686'
color9='#218D75'
color10='#239D82'
color11='#23B292'
color12='#7F8080'
color13='#24C19F'
color14='#24D1AC'
color15='#c0c0c0'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
