mkdir audio
mkdir audio/music
mkdir audio/records
mkdir audio/songs
mkdir img
mkdir img/stock
mkdir img/diy
mkdir videos
mkdir videos/stock
mkdir videos/diy
mkdir videos/diy/toonz
touch sauce.txt
touch notes.txt
